# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.28.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.28.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/gkiran/MS UCSB/CS 260/CS-260-Program-Analysis"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/gkiran/MS UCSB/CS 260/CS-260-Program-Analysis"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.28.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.28.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/gkiran/MS UCSB/CS 260/CS-260-Program-Analysis/CMakeFiles" "/Users/gkiran/MS UCSB/CS 260/CS-260-Program-Analysis//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/gkiran/MS UCSB/CS 260/CS-260-Program-Analysis/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named assn5_taint_analysis

# Build rule for target.
assn5_taint_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assn5_taint_analysis
.PHONY : assn5_taint_analysis

# fast build rule for target.
assn5_taint_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assn5_taint_analysis.dir/build.make CMakeFiles/assn5_taint_analysis.dir/build
.PHONY : assn5_taint_analysis/fast

taint-analysis/taint_analysis.o: taint-analysis/taint_analysis.cpp.o
.PHONY : taint-analysis/taint_analysis.o

# target to build an object file
taint-analysis/taint_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assn5_taint_analysis.dir/build.make CMakeFiles/assn5_taint_analysis.dir/taint-analysis/taint_analysis.cpp.o
.PHONY : taint-analysis/taint_analysis.cpp.o

taint-analysis/taint_analysis.i: taint-analysis/taint_analysis.cpp.i
.PHONY : taint-analysis/taint_analysis.i

# target to preprocess a source file
taint-analysis/taint_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assn5_taint_analysis.dir/build.make CMakeFiles/assn5_taint_analysis.dir/taint-analysis/taint_analysis.cpp.i
.PHONY : taint-analysis/taint_analysis.cpp.i

taint-analysis/taint_analysis.s: taint-analysis/taint_analysis.cpp.s
.PHONY : taint-analysis/taint_analysis.s

# target to generate assembly for a file
taint-analysis/taint_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/assn5_taint_analysis.dir/build.make CMakeFiles/assn5_taint_analysis.dir/taint-analysis/taint_analysis.cpp.s
.PHONY : taint-analysis/taint_analysis.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... assn5_taint_analysis"
	@echo "... taint-analysis/taint_analysis.o"
	@echo "... taint-analysis/taint_analysis.i"
	@echo "... taint-analysis/taint_analysis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

